<a href="https://colab.research.google.com/github/aleenalasarin/Datascience-ML-AI-BigData-Cloud-Visualizations/blob/main/KNN_stroke.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/healthcare-dataset-stroke-data.csv')
df

id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes   
1     51676  Female  61.0             0              0          Yes   
2     31112    Male  80.0             0              1          Yes   
3     60182  Female  49.0             0              0          Yes   
4      1665  Female  79.0             1              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5105  18234  Female  80.0             1              0          Yes   
5106  44873  Female  81.0             0              0          Yes   
5107  19723  Female  35.0             0              0          Yes   
5108  37544    Male  51.0             0              0          Yes   
5109  44679  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked   
1     Self-employed          Rural             202.21   NaN     never smoked   
2           Private          Rural             105.92  32.5     never smoked   
3           Private          Urban             171.23  34.4           smokes   
4     Self-employed          Rural             174.12  24.0     never smoked   
...             ...            ...                ...   ...              ...   
5105        Private          Urban              83.75   NaN     never smoked   
5106  Self-employed          Urban             125.20  40.0     never smoked   
5107  Self-employed          Rural              82.99  30.6     never smoked   
5108        Private          Rural             166.29  25.6  formerly smoked   
5109       Govt_job          Urban              85.28  26.2          Unknown   

      stroke  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
5105       0  
5106       0  
5107       0  
5108       0  
5109       0  

[5110 rows x 12 columns]

In [ ]:
df.head()

id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes   
1  51676  Female  61.0             0              0          Yes   
2  31112    Male  80.0             0              1          Yes   
3  60182  Female  49.0             0              0          Yes   
4   1665  Female  79.0             1              0          Yes   

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked   
1  Self-employed          Rural             202.21   NaN     never smoked   
2        Private          Rural             105.92  32.5     never smoked   
3        Private          Urban             171.23  34.4           smokes   
4  Self-employed          Rural             174.12  24.0     never smoked   

   stroke  
0       1  
1       1  
2       1  
3       1  
4       1

In [ ]:
df.tail()

id  gender   age  hypertension  heart_disease ever_married  \
5105  18234  Female  80.0             1              0          Yes   
5106  44873  Female  81.0             0              0          Yes   
5107  19723  Female  35.0             0              0          Yes   
5108  37544    Male  51.0             0              0          Yes   
5109  44679  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
5105        Private          Urban              83.75   NaN     never smoked   
5106  Self-employed          Urban             125.20  40.0     never smoked   
5107  Self-employed          Rural              82.99  30.6     never smoked   
5108        Private          Rural             166.29  25.6  formerly smoked   
5109       Govt_job          Urban              85.28  26.2          Unknown   

      stroke  
5105       0  
5106       0  
5107       0  
5108       0  
5109       0

In [ ]:
df.columns

Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

In [ ]:
df.dtypes


id                     int64
gender                object
age                  float64
hypertension           int64
heart_disease          int64
ever_married          object
work_type             object
Residence_type        object
avg_glucose_level    float64
bmi                  float64
smoking_status        object
stroke                 int64
dtype: object

In [ ]:
df.isna().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [ ]:
x=df['bmi'].mean()
x
df['bmi'].fillna(x,inplace=True)
df.isna().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [ ]:
df.drop(['id'],axis=1,inplace=True)


In [ ]:
df.isna().sum()

gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [ ]:
df.drop(['gender'],axis=1,inplace=True)

In [ ]:
df.isna().sum()

age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [ ]:
df.drop(['work_type'],axis=1,inplace=True)

In [ ]:
df.isna().sum()

age                  0
hypertension         0
heart_disease        0
ever_married         0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [ ]:
df.drop(['ever_married'],axis=1,inplace=True)

In [ ]:
df.isna().sum()

age                  0
hypertension         0
heart_disease        0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [ ]:
df.drop(['Residence_type'],axis=1,inplace=True)

In [ ]:
df.isna().sum()

age                  0
hypertension         0
heart_disease        0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [ ]:
df.dtypes

age                  float64
hypertension           int64
heart_disease          int64
avg_glucose_level    float64
bmi                  float64
smoking_status        object
stroke                 int64
dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
df['smoking_status']=lab.fit_transform(df['smoking_status'])
df

age  hypertension  heart_disease  avg_glucose_level        bmi  \
0     67.0             0              1             228.69  36.600000   
1     61.0             0              0             202.21  28.893237   
2     80.0             0              1             105.92  32.500000   
3     49.0             0              0             171.23  34.400000   
4     79.0             1              0             174.12  24.000000   
...    ...           ...            ...                ...        ...   
5105  80.0             1              0              83.75  28.893237   
5106  81.0             0              0             125.20  40.000000   
5107  35.0             0              0              82.99  30.600000   
5108  51.0             0              0             166.29  25.600000   
5109  44.0             0              0              85.28  26.200000   

      smoking_status  stroke  
0                  1       1  
1                  2       1  
2                  2       1  
3                  3       1  
4                  2       1  
...              ...     ...  
5105               2       0  
5106               2       0  
5107               2       0  
5108               1       0  
5109               0       0  

[5110 rows x 7 columns]

In [ ]:
x=df.iloc[:,:-1].values
x

array([[ 67.        ,   0.        ,   1.        , 228.69      ,
         36.6       ,   1.        ],
       [ 61.        ,   0.        ,   0.        , 202.21      ,
         28.89323691,   2.        ],
       [ 80.        ,   0.        ,   1.        , 105.92      ,
         32.5       ,   2.        ],
       ...,
       [ 35.        ,   0.        ,   0.        ,  82.99      ,
         30.6       ,   2.        ],
       [ 51.        ,   0.        ,   0.        , 166.29      ,
         25.6       ,   1.        ],
       [ 44.        ,   0.        ,   0.        ,  85.28      ,
         26.2       ,   0.        ]])

In [ ]:
y=df.iloc[:,-1].values
y

array([1, 1, 1, ..., 0, 0, 0])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[  4.  ,   0.  ,   0.  ,  90.42,  16.2 ,   0.  ],
       [ 29.  ,   0.  ,   0.  , 207.58,  22.8 ,   3.  ],
       [ 44.  ,   1.  ,   0.  ,  91.28,  26.5 ,   2.  ],
       ...,
       [  1.16,   0.  ,   0.  ,  97.28,  17.8 ,   0.  ],
       [ 80.  ,   0.  ,   0.  , 196.08,  31.  ,   1.  ],
       [ 46.  ,   0.  ,   0.  , 100.15,  50.3 ,   3.  ]])

In [ ]:
x_test

array([[31.  ,  0.  ,  0.  , 64.85, 23.  ,  0.  ],
       [40.  ,  0.  ,  0.  , 65.29, 28.3 ,  2.  ],
       [ 8.  ,  0.  ,  0.  , 74.42, 22.5 ,  0.  ],
       ...,
       [42.  ,  0.  ,  0.  , 93.79, 27.2 ,  2.  ],
       [57.  ,  0.  ,  0.  , 69.4 , 24.  ,  0.  ],
       [60.  ,  0.  ,  0.  , 73.04, 25.3 ,  2.  ]])

In [ ]:
y_train

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
y_test

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[-1.7467638 , -0.31719928, -0.23946931, -0.340693  , -1.65003512,
        -1.29622579],
       [-0.63635252, -0.31719928, -0.23946931,  2.26654137, -0.79238754,
         1.52066342],
       [ 0.02989425,  3.15259225, -0.23946931, -0.32155489, -0.31158512,
         0.58170035],
       ...,
       [-1.87290652, -0.31719928, -0.23946931, -0.18803315, -1.44212056,
        -1.29622579],
       [ 1.62888649, -0.31719928, -0.23946931,  2.01062472,  0.27317459,
        -0.35726272],
       [ 0.11872715, -0.31719928, -0.23946931, -0.12416526,  2.78114402,
         1.52066342]])

In [ ]:
x_test

array([[-0.54751962, -0.31719928, -0.23946931, -0.90971812, -0.76639822,
        -1.29622579],
       [-0.14777156, -0.31719928, -0.23946931, -0.89992653, -0.07768123,
         0.58170035],
       [-1.569098  , -0.31719928, -0.23946931, -0.69675096, -0.83137152,
        -1.29622579],
       ...,
       [-0.05893866, -0.31719928, -0.23946931, -0.26569829, -0.22062249,
         0.58170035],
       [ 0.60730811, -0.31719928, -0.23946931, -0.80846414, -0.63645162,
        -1.29622579],
       [ 0.74055746, -0.31719928, -0.23946931, -0.72746095, -0.46752104,
         0.58170035]])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier()
model.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
y_test

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[1440,    4],
       [  89,    0]])

In [ ]:
score=accuracy_score(y_test,y_pred)
score

0.9393346379647749